version: '3.1'

services:
  db:
    build: ./database
    container_name: postgres
    restart: always
    ports:
      - "5440:5432"

  weather:
    build: ./
    container_name: weather
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db